[okta_mcp_servers]
127.0.0.1 ansible_port=10035 ansible_user=ec2-user

[okta_mcp_servers:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
aws_region=eu-west-3