[okta_mcp_servers]
10.2.0.39 ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/your-key.pem

[okta_mcp_servers:vars]
ansible_python_interpreter=/usr/bin/python3
aws_region=eu-west-3
instance_id=i-0a71c3f35795cf260
