---
# AWS Configuration
aws_region: "eu-west-3"

# Secret IDs
readonly_secret_id: "arn:aws:secretsmanager:eu-west-3:306965385748:secret:okta-mcp-readonly-private-key-prod-K8i8L2"
admin_secret_id: "arn:aws:secretsmanager:eu-west-3:306965385748:secret:okta-mcp-admin-private-key-prod-Abcj5Z"
litellm_master_secret_id: "arn:aws:secretsmanager:eu-west-3:306965385748:secret:litellm-master-key-20260128123932657700000001-p1aAwa"
litellm_admin_secret_id: "arn:aws:secretsmanager:eu-west-3:306965385748:secret:litellm-admin-team-key-20260128123932658100000005-puD7RV"
litellm_reader_secret_id: "arn:aws:secretsmanager:eu-west-3:306965385748:secret:litellm-reader-team-key-20260128123932933300000009-6ua86p"

# Okta Configuration
okta_api_base_url: "https://integrator-7772662.okta.com"
okta_readonly_client_id: "0oay0b661jlQnwFJG697"
okta_readonly_scopes: "okta.users.read okta.groups.read okta.apps.read okta.logs.read"
okta_admin_client_id: "0oay0p5kq9WhsKa9c697"
okta_admin_scopes: "okta.users.manage okta.groups.manage okta.apps.manage"

# Docker
docker_image: "blackstaa/okta-mcp-server:latest"
