---
# AWS Configuration
aws_region: "eu-west-3"

# Okta AI Agent Secret IDs
readonly_secret_id: "arn:aws:secretsmanager:eu-west-3:306965385748:secret:okta-mcp-readonly-private-key-prod-K8i8L2"
admin_secret_id: "arn:aws:secretsmanager:eu-west-3:306965385748:secret:okta-mcp-admin-private-key-prod-Abcj5Z"
litellm_master_secret_id: "arn:aws:secretsmanager:eu-west-3:306965385748:secret:litellm-master-key-20260128123932657700000001-p1aAwa"
litellm_admin_secret_id: "arn:aws:secretsmanager:eu-west-3:306965385748:secret:litellm-admin-team-key-20260128123932658100000005-puD7RV"
litellm_reader_secret_id: "arn:aws:secretsmanager:eu-west-3:306965385748:secret:litellm-reader-team-key-20260128123932933300000009-6ua86p"

# Github runner Secret IDs
github_runner_app_private_key_secret_id: "arn:aws:secretsmanager:eu-west-3:306965385748:secret:github-runner-app-private-key-pUo6RP"
github_runner_app_installation_id_secret_id: "arn:aws:secretsmanager:eu-west-3:306965385748:secret:github-runner-app-installation-id-18d3TO"
github_runner_app_id_secret_id: "arn:aws:secretsmanager:eu-west-3:306965385748:secret:github-runner-app-id-Ywy4zB"

# Okta Configuration
okta_api_base_url: "https://kaltura.okta.com"
okta_readonly_client_id: "0oa25ucjxsjaMTjO40h8"
okta_readonly_scopes: "okta.users.read okta.groups.read okta.apps.read okta.logs.read"
okta_admin_client_id: "0oa25ucksrp2GU6rs0h8"
okta_admin_scopes: "okta.users.manage okta.groups.manage okta.logs.read okta.apps.manage okta.apps.read"

# Service versions
litellm_version: "main-v1.81.12-stable.2"
loki_version: "3.4.3"
alloy_version: "v1.7.5"
grafana_version: "12.0.2"
redis_version: "7.4.8-alpine"
postgres_version: "16-alpine"

# Bedrock model
bedrock_model_id: "bedrock/eu.anthropic.claude-sonnet-4-5-20250929-v1:0"


docker_image: "blackstaa/okta-mcp-server:latest"

# PostgreSQL - LiteLLM database
litellm_db_user: "litellm"
litellm_db_name: "litellm"


# RDS master connection (for schema setup)
rds_host: "okta-orchestrator-db.cxvxlfb3g9aw.eu-west-3.rds.amazonaws.com"
rds_master_user: "orchestrator"
rds_db_password_secret_id: "arn:aws:secretsmanager:eu-west-3:306965385748:secret:okta-orchestrator-db-password-Q9XPIF"

# EBS Mount point
application_directory: /opt/okta-litellm
storage_directory: /opt/okta-litellm/data
persistent_volume_uuid: 649c4395-6ae6-4485-b2af-f9a16c1910e0